server:
  port: 20001

spring:
  application:
    name: api-gateway

  # spring.cloud.gateway.mvc.routes
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-server
            uri: http://localhost:20002
            predicates:
              - Path=/auth/v1/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG